/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/dmkReZo3GhU
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div key="1" className="flex flex-col min-h-[100dvh]">
      <section className="w-full py-6 md:py-12 xl:py-16">
        <div className="container flex flex-col items-center justify-center gap-2 px-4 text-center md:gap-4 md:px-6">
          <div className="space-y-2">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Protecting your future</h1>
            <p className="max-w-[800px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Let me help you secure your family's financial well-being. Trusted advisor. Peace of mind.
            </p>
          </div>
          <div className="flex flex-col gap-2 min-[400px]:flex-row">
            <Link
              className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 border-gray-200 bg-white px-8 text-sm font-medium shadow-sm gap-2 sm:gap-3 md:gap-2 hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-950 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300"
              href="#"
            >
              Contact me
            </Link>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">My Achievements</h2>
            <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Recognized for excellence. Committed to your security.
            </p>
          </div>
          <div className="mx-auto w-full max-w-[800px] grid gap-6 lg:grid-cols-2">
            <div className="flex flex-col gap-2">
              <img
                alt="Achievement"
                className="aspect-video overflow-hidden rounded-xl object-cover object-center"
                height="400"
                src="/placeholder.svg"
                width="600"
              />
              <div className="space-y-2">
                <h3 className="text-2xl font-bold tracking-tight">Top Performer Award</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Awarded for exceptional service and dedication to my clients' well-being.
                </p>
              </div>
            </div>
            <div className="flex flex-col gap-2">
              <img
                alt="Achievement"
                className="aspect-video overflow-hidden rounded-xl object-cover object-center"
                height="400"
                src="/placeholder.svg"
                width="600"
              />
              <div className="space-y-2">
                <h3 className="text-2xl font-bold tracking-tight">Community Leader Recognition</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Honored for my involvement in community outreach and education on financial planning.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
        <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">What my clients say</h2>
            <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Trusted by the best teams in the world. We help teams of all sizes.
            </p>
          </div>
          <div className="mx-auto w-full max-w-[400px]">
            <div className="grid w-full grid-rows-3 items-stretch justify-center gap-4 sm:grid-rows-1 sm:grid-cols-3 sm:gap-8">
              <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
                <img
                  alt="Avatar"
                  className="rounded-full"
                  height="150"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "150/150",
                    objectFit: "cover",
                  }}
                  width="150"
                />
              </div>
              <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
                <img
                  alt="Avatar"
                  className="rounded-full"
                  height="150"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "150/150",
                    objectFit: "cover",
                  }}
                  width="150"
                />
              </div>
              <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
                <img
                  alt="Avatar"
                  className="rounded-full"
                  height="150"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "150/150",
                    objectFit: "cover",
                  }}
                  width="150"
                />
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">About Me</h2>
            <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              I've been helping families protect their financial future for over a decade. Let me put my expertise to
              work for you.
            </p>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 border-t">
        <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Contact Me</h2>
            <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Ready to take the next step? Let's talk about how we can protect your family's future.
            </p>
          </div>
          <div className="mx-auto w-full max-w-[400px] space-y-4">
            <form className="grid gap-4">
              <Input className="w-full" placeholder="Name" type="text" />
              <Input className="w-full" placeholder="Email" type="email" />
              <Input className="w-full" placeholder="Phone number" type="text" />
              <Textarea className="w-full" placeholder="Message" />
              <Button className="w-full" type="submit">
                Submit
              </Button>
            </form>
          </div>
        </div>
      </section>
    </div>
  )
}
